### ISSUE TITLE
AdminHomeView does not display scheduled stretches

### ISSUE THREAD

**Issue by ydhan18** [snippet-good/snippet-good#39]
In ``mapStateToProps()`` in ``AdminHomeView`` component:

```
const { open, scheduled } = getFilteredStretchesOfAdmin(
    userDetails.id,
    cohortStretches,
    stretches,
    users,
    stretchAnswers
)
```

variable ``scheduled`` is returning as an empty array.

**Comment by slevine111** [comment]
@ydhan18 it's working for me. You want to screen share to show me what your are seeing? What seed file are you using? The improved seed.js file is gauranteed ot have a scheduled stretch for every admin

**Comment by ydhan18** [comment]
I think it would be better if we can video chat later today. And I was using ``seed2.js``, which might be the issue since I have no ``stretchAnswers`` on this seed.
